name: YouTube Bot Automation

on:
  workflow_dispatch:

jobs:
  youtube-bot:
    runs-on: windows-latest
    strategy:
      matrix:
        account:
          - "JilliBeckzuf57890h@vasim.org|Hello9999"
          - "LilyanVaughanrbl36662o@vasim.org|Hello9999"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
     
      - name: Cache EasyOCR models
        uses: actions/cache@v4
        with:
          path: C:\Users\runneradmin\.EasyOCR
          key: easyocr-models
      
      - name: Install dependencies
        run: |
           python -m pip install --upgrade pip
      - name: Install dependencies
        run: |
          pip install --no-python-version-warning -r requirements.txt
      - name: Run YouTube Bot
        run: python main.py "${{ matrix.account }}"
        env:
            PYTHONUTF8: 1
